name: Define Your LongPlay - gr0ourSource
description: Share the song and three book quotes that will inform our Language Institution and define your persona in huStory.
title: "[gr0ourSource Definition] <name of you/your project>"
labels: ["good first issue"]
body:
  - type: markdown
    attributes:
      value: |
        In huStory, all of the posts we share are called beats. They represent the DNA of the LongPlays that we grow. LongPlays are Kalpavriksha Forest Gardens that we grow in our minds. LP0_polymathProcess is focused on decentralizing our language system with chill music and meaningful book quotes. In the huniverse, adding the following three book quotes represent prophase in this LongPlay's cell division.
  - type: input
    id: gr0v0song
    attributes:
      label: gr0v0song_
      description: Choose a song that will introduce your LongPlay. This song helps defines the water quality for your LP and can always be changed at a later date. Format [Song Name] by [Artist Name1, Artist Name2, etc.]
      placeholder: "0.00 by Childish Gambino"
    validations:
      required: true
