name: Define Your LongPlay - gr0ourSource
description: Share the song and three book quotes that will inform our Language Institution and define your persona in huStory.
title: "[gr0ourSource Definition] <name of you/your project>"
labels: "good first issue"
body:
  - type: markdown
    attributes:
      value: In huStory, all of the posts we share are called beats. They represent the DNA of the LongPlays that we grow. LongPlays are Kalpavriksha Forest Gardens that we grow in our minds. LP0_polymathProcess is focused on decentralizing our language system with chill music and meaningful book quotes. In the huniverse, adding the following three book quotes represent prophase in this LongPlay's cell division.
  - type: input
    id: gr0v0song
    attributes:
      label: gr0v0song_
      description: Choose a song that will introduce your LongPlay. This song helps defines the water quality for your LP and can always be changed at a later date. Format [Song Name] by [Artist Name1, Artist Name2, etc.]
      placeholder: "0.00 by Childish Gambino"
    validations:
      required: true
      
  - type: input
    id: gr0v1biomimicry
    attributes:
      label: gr0v1biomimicry_
      description: Choose a book title related to the human body or human experience.
      placeholder: "The Polymath by Waqas Ahmed"
    validations:
      required: true
      
  - type: input
    id: gr0v2ego
    attributes:
      label: gr0v2ego_
      description: Choose a book title that outlines characteristics you and your project strive for.
      placeholder: "A New Earth by Eckhart Tolle"
    validations:
      required: true
      
  - type: input
    id: gr0v3mission
    attributes:
      label: gr0v3mission_
      description: Choose a book title that will set the tone for how you and your project take action.
      placeholder: "Tao Te Ching by Lao Tzu"
    validations: true
Once cell division is completed, poly's consciousness/awareness has expanded (new soil particle, new water molecule, and new hu3agent in the huniverse)
