name: Define huStory's Setting
description: Share the song and three book quotes that will inform our Language Institution and define your persona in huStory.
title: "[gr0ourSource Definition] <name of you/your project>"
labels: ["polymathProcess"]
body:
  - type: markdown
    attributes:
      value: |
        Completing the form below kicks off the process for creating your own LongPlay in the huniverse.
  - type: input
    id: gr0-ego-human-system
    attributes:
      label: gr0ourSource_ego
      description: Humans subconsciously modeled our Language Institution from what concept or system? 
      placeholder: ex. The Tao, the Universe, etc.
      value: "The Tao (default)"
    validations:
      required: true

Intro: In huStory, all of the posts we share are called beats. They represent the DNA of the LongPlays that we grow. LongPlays are Kalpavriksha Forest Gardens that we learn how to grow in our minds. LP0_polymathProcess is focused on decentralizing our language system with chill music and meaningful book quotes. In the huniverse, adding the following three book quotes represent prophase in this LongPlay's cell division.
Prophase
Prophase gr0v0ego (soil) header and quote used for this example by polymathProcess
Input gr0v0ego quote
Prophase gr0v1biomimicry (water) header and quote used for this example by polymathProcess
Input gr0v1biomimicry quote
Prophase gr0v2willpower (you/hu) header and quote used for this example by polymathProcess
Input gr0v2willpower quote
Metaphase
Metaphase gr0ourSource header and song used for this step by polymathProcess
Anaphase
Anaphase is initiated once the issue is submitted. Existing hu3agents will design and package your beats
Graphic designers create quote cards from shared Figma file
Writers layer in a narrative in the comments
Post for book quote 0 (polymathProcess explaining the call to action), 1 (ournOrm showing what poly needed to find), 2 (hu3agency writeup explaining the whole story), and the song (multipleVerses post as the full narrative)
Telophase: Quotes are shared to polymathProcess, ournOrm, and hu3agency
Cytokinesis: New hu3agency creates a guide on their instagram using the posts from polymathProcess, ournOrm, hu3agency, and multipleVerses
Once cell division is completed, poly's consciousness/awareness has expanded (new soil particle, new water molecule, and new hu3agent in the huniverse)
